In [2]:
import numpy as np
arr=np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
np.random.randint(1,100,10)

array([59, 48, 85, 19, 72, 82, 18,  5, 93, 83])

In [7]:
#100 , 200 - 100
np.random.randint(100,200,size=(2,30,20))

array([[[195, 135, 143, ..., 169, 123, 195],
        [151, 146, 135, ..., 189, 154, 173],
        [100, 170, 143, ..., 134, 116, 187],
        ...,
        [141, 163, 104, ..., 150, 147, 158],
        [192, 166, 164, ..., 133, 138, 198],
        [181, 119, 166, ..., 173, 110, 115]],

       [[181, 146, 195, ..., 177, 161, 172],
        [144, 153, 129, ..., 161, 103, 150],
        [100, 132, 129, ..., 153, 177, 122],
        ...,
        [114, 118, 162, ..., 153, 160, 195],
        [159, 180, 185, ..., 124, 199, 101],
        [189, 116, 153, ..., 153, 133, 126]]])

In [9]:
#20,50--- 4 dimension
arr=np.random.randint(20,50,size=(4,5,2,3))
arr

array([[[[49, 43, 39],
         [25, 40, 29]],

        [[24, 26, 31],
         [31, 46, 25]],

        [[43, 29, 42],
         [25, 44, 34]],

        [[22, 24, 22],
         [22, 36, 21]],

        [[35, 23, 39],
         [26, 44, 21]]],


       [[[40, 27, 23],
         [40, 39, 31]],

        [[43, 28, 45],
         [33, 25, 45]],

        [[39, 44, 28],
         [25, 35, 40]],

        [[34, 39, 21],
         [28, 20, 24]],

        [[30, 44, 37],
         [30, 43, 33]]],


       [[[25, 26, 22],
         [43, 43, 36]],

        [[32, 21, 32],
         [47, 26, 44]],

        [[43, 39, 34],
         [39, 20, 23]],

        [[37, 20, 49],
         [42, 41, 27]],

        [[40, 25, 27],
         [35, 30, 30]]],


       [[[37, 27, 43],
         [39, 41, 44]],

        [[40, 47, 44],
         [37, 32, 42]],

        [[27, 32, 48],
         [38, 42, 21]],

        [[30, 45, 22],
         [28, 20, 33]],

        [[38, 47, 39],
         [21, 26, 20]]]])

In [13]:
arr3=arr.reshape(3,4,10)

In [11]:
arr3

array([[[49, 43, 39, 25, 40, 29, 24, 26, 31, 31],
        [46, 25, 43, 29, 42, 25, 44, 34, 22, 24],
        [22, 22, 36, 21, 35, 23, 39, 26, 44, 21],
        [40, 27, 23, 40, 39, 31, 43, 28, 45, 33]],

       [[25, 45, 39, 44, 28, 25, 35, 40, 34, 39],
        [21, 28, 20, 24, 30, 44, 37, 30, 43, 33],
        [25, 26, 22, 43, 43, 36, 32, 21, 32, 47],
        [26, 44, 43, 39, 34, 39, 20, 23, 37, 20]],

       [[49, 42, 41, 27, 40, 25, 27, 35, 30, 30],
        [37, 27, 43, 39, 41, 44, 40, 47, 44, 37],
        [32, 42, 27, 32, 48, 38, 42, 21, 30, 45],
        [22, 28, 20, 33, 38, 47, 39, 21, 26, 20]]])

In [14]:
arr3.shape

(3, 4, 10)

In [15]:
arr3.ravel() #arr3.flatten()

array([49, 43, 39, 25, 40, 29, 24, 26, 31, 31, 46, 25, 43, 29, 42, 25, 44,
       34, 22, 24, 22, 22, 36, 21, 35, 23, 39, 26, 44, 21, 40, 27, 23, 40,
       39, 31, 43, 28, 45, 33, 25, 45, 39, 44, 28, 25, 35, 40, 34, 39, 21,
       28, 20, 24, 30, 44, 37, 30, 43, 33, 25, 26, 22, 43, 43, 36, 32, 21,
       32, 47, 26, 44, 43, 39, 34, 39, 20, 23, 37, 20, 49, 42, 41, 27, 40,
       25, 27, 35, 30, 30, 37, 27, 43, 39, 41, 44, 40, 47, 44, 37, 32, 42,
       27, 32, 48, 38, 42, 21, 30, 45, 22, 28, 20, 33, 38, 47, 39, 21, 26,
       20])

In [ ]:
#random --
#real number -> integer (positive, negative , zero)
#decimal -> . float, double 

In [16]:
np.random.uniform(1,10,size=10)

array([4.41780892, 1.15537115, 3.82216928, 1.83244593, 3.11385475,
       8.30534449, 4.06147932, 9.9892423 , 3.6787707 , 7.77764076])

In [18]:
# float -> 3 di random number
np.random.uniform(1,20,size=(2,3,5))

array([[[11.14175687, 18.39897313,  2.9915672 ,  7.97443388,
          7.62155664],
        [ 6.87752222,  3.08644718, 10.67045539, 19.50654047,
         17.40607272],
        [ 6.5274525 ,  6.01427582,  9.80367539, 10.60729955,
          9.65437994]],

       [[15.94222543,  2.59025353,  2.18806762, 11.89802012,
         17.76197012],
        [17.51014674, 11.29457017,  6.80273145,  1.38389365,
         14.65612253],
        [ 3.44407548,  1.30382286, 16.36790566, 17.30750482,
         10.53905512]]])

In [25]:
arr=np.random.randint(1,100,size=100)
arr

array([75, 93, 30, 11,  4, 23, 37, 84,  4, 94, 45, 86, 83, 84, 75, 86, 58,
       14, 49, 52, 90, 55, 55, 16, 54, 80, 73, 35, 98, 30, 32,  2, 55, 43,
       71, 45, 40, 91, 54, 97, 55, 50, 88, 13, 26, 72, 17, 10, 81, 71, 96,
       24, 20, 48, 46, 55, 92, 29, 24, 66, 52, 83, 49,  8, 82, 30, 92, 39,
       86, 96, 53, 70, 81, 79, 45, 92, 89, 28,  1,  7,  5, 20, 37, 13,  3,
       96, 82, 72, 43, 91, 16, 45, 22, 55, 49, 66, 29, 81, 42, 83])

In [21]:
#array indexing/slicing -> number indexing, conditional indexing
#number indexing
arr[5]

41

In [22]:
arr[0:5] #start,end


array([53, 78, 74, 16, 77])

In [23]:
arr[:5]

array([53, 78, 74, 16, 77])

In [26]:
#arr[::]#start,end,step
arr[10:40:3] #-->forward

array([45, 84, 58, 52, 55, 80, 98,  2, 71, 91])

In [27]:
arr[::-1]

array([83, 42, 81, 29, 66, 49, 55, 22, 45, 16, 91, 43, 72, 82, 96,  3, 13,
       37, 20,  5,  7,  1, 28, 89, 92, 45, 79, 81, 70, 53, 96, 86, 39, 92,
       30, 82,  8, 49, 83, 52, 66, 24, 29, 92, 55, 46, 48, 20, 24, 96, 71,
       81, 10, 17, 72, 26, 13, 88, 50, 55, 97, 54, 91, 40, 45, 71, 43, 55,
        2, 32, 30, 98, 35, 73, 80, 54, 16, 55, 55, 90, 52, 49, 14, 58, 86,
       75, 84, 83, 86, 45, 94,  4, 84, 37, 23,  4, 11, 30, 93, 75])

In [28]:
arr[::-4] #start, end, step

array([83, 66, 45, 72, 13,  7, 92, 70, 39,  8, 66, 55, 24, 10, 13, 97, 45,
        2, 35, 16, 52, 86, 86, 84, 11])

In [29]:
arr[40:10:-2]

array([55, 54, 40, 71, 55, 32, 98, 73, 54, 55, 90, 49, 58, 75, 83])

In [30]:
arr[10:40:-2]

array([], dtype=int32)

In [31]:
#conditional/boolean indexing
arr[arr>50]

array([75, 93, 84, 94, 86, 83, 84, 75, 86, 58, 52, 90, 55, 55, 54, 80, 73,
       98, 55, 71, 91, 54, 97, 55, 88, 72, 81, 71, 96, 55, 92, 66, 52, 83,
       82, 92, 86, 96, 53, 70, 81, 79, 92, 89, 96, 82, 72, 91, 55, 66, 81,
       83])

In [32]:
arr[arr%2==0] #short-hand

array([30,  4, 84,  4, 94, 86, 84, 86, 58, 14, 52, 90, 16, 54, 80, 98, 30,
       32,  2, 40, 54, 50, 88, 26, 72, 10, 96, 24, 20, 48, 46, 92, 24, 66,
       52,  8, 82, 30, 92, 86, 96, 70, 92, 28, 20, 96, 82, 72, 16, 22, 66,
       42])

In [33]:
#statistic information
arr

array([75, 93, 30, 11,  4, 23, 37, 84,  4, 94, 45, 86, 83, 84, 75, 86, 58,
       14, 49, 52, 90, 55, 55, 16, 54, 80, 73, 35, 98, 30, 32,  2, 55, 43,
       71, 45, 40, 91, 54, 97, 55, 50, 88, 13, 26, 72, 17, 10, 81, 71, 96,
       24, 20, 48, 46, 55, 92, 29, 24, 66, 52, 83, 49,  8, 82, 30, 92, 39,
       86, 96, 53, 70, 81, 79, 45, 92, 89, 28,  1,  7,  5, 20, 37, 13,  3,
       96, 82, 72, 43, 91, 16, 45, 22, 55, 49, 66, 29, 81, 42, 83])

In [34]:
arr.sum()

5298

In [35]:
arr.max()

98

In [36]:
arr.min()

1

In [37]:
arr.mean()

52.98

In [38]:
arr1=np.random.randint(1,100,10)
arr2=np.random.randint(1,100,10)
print(arr1)
print(arr2)

[62 29 61 72 19 64 45 50 85 79]
[46 58 82 54 12 13 28 38 23 78]


In [39]:
arr1+arr2

array([108,  87, 143, 126,  31,  77,  73,  88, 108, 157])

In [40]:
np.add(arr1,arr2)

array([108,  87, 143, 126,  31,  77,  73,  88, 108, 157])

In [41]:
np.subtract(arr1,arr2)

array([ 16, -29, -21,  18,   7,  51,  17,  12,  62,   1])

In [45]:
arr1*arr2

array([2852, 1682, 5002, 3888,  228,  832, 1260, 1900, 1955, 6162])

In [46]:
arr1/arr2

array([1.34782609, 0.5       , 0.74390244, 1.33333333, 1.58333333,
       4.92307692, 1.60714286, 1.31578947, 3.69565217, 1.01282051])

In [47]:
arr1=np.random.randint(1,20,size=(3,4))
arr2=np.random.randint(1,20,size=(4,2))
print(arr1)
print(arr2)

[[ 4 13 11  2]
 [ 7 18 17  2]
 [18  9  2  8]]
[[ 1 15]
 [ 1  4]
 [12  1]
 [ 6 19]]


In [48]:
arr1.shape

(3, 4)

In [49]:
arr2.shape

(4, 2)

In [51]:
np.matmul(arr1,arr2)

array([[161, 161],
       [241, 232],
       [ 99, 460]])

In [52]:
arr1

array([[ 4, 13, 11,  2],
       [ 7, 18, 17,  2],
       [18,  9,  2,  8]])

In [53]:
arr1.max()

18

In [54]:
arr1.max(axis=1) #row

array([13, 18, 18])

In [55]:
arr1.max(axis=0) #column

array([18, 18, 17,  8])

In [56]:
#slicing
arr1[:2]

array([[ 4, 13, 11,  2],
       [ 7, 18, 17,  2]])

In [57]:
arr1[:-1]

array([[ 4, 13, 11,  2],
       [ 7, 18, 17,  2]])

In [58]:
arr1[::,::]

array([[ 4, 13, 11,  2],
       [ 7, 18, 17,  2],
       [18,  9,  2,  8]])

In [60]:
arr1[:2,2:]

array([[11,  2],
       [17,  2]])

In [62]:
arr1[1:,1:]

array([[18, 17,  2],
       [ 9,  2,  8]])

In [63]:
#ellipsis
arr1[...,1]

array([13, 18,  9])

In [ ]:
#structure data
#csv, excel, tsv  -> pandas - library
#text, word ,data -> file IO

In [ ]:
!pip install pandas

In [64]:
import pandas as pd
pd.__version__

'1.5.3'

In [65]:
data=pd.read_csv('All_Pokemon.csv')
data

Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  Against Bug  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...          1.0   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...          1.0   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...          1.0   
3                   ['Thick Fat']   80  100  123  122  120  ...          1.0   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...          0.5   
...                           ...  ...  ...  ...  ...  ...  ...          ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...          1.0   
1028               ['Grim Neigh']  100   65   60  145   80  ...          0.5   
1029                  ['Unnerve']  100   80   80   80   80  ...          4.0   
1030                   ['As One']  100  165  150   85  130  ...          2.0   
1031                   ['As One']  100   85   80  165  100  ...          1.0   

      Against Rock  Against Ghost  Against Dragon  Against Dark Against Steel  \
0              1.0            1.0             1.0           1.0           1.0   
1              1.0            1.0             1.0           1.0           1.0   
2              1.0            1.0             1.0           1.0           1.0   
3              1.0            1.0             1.0           1.0           1.0   
4              2.0            1.0             1.0           1.0           0.5   
...            ...            ...             ...           ...           ...   
1027           2.0            1.0             1.0           1.0           2.0   
1028           1.0            2.0             1.0           2.0           1.0   
1029           1.0            2.0             1.0           2.0           1.0   
1030           2.0            2.0             1.0           2.0           2.0   
1031           1.0            4.0             1.0           4.0           1.0   

      Against Fairy  Height  Weight    BMI  
0               0.5     0.7     6.9   14.1  
1               0.5     1.0    13.0   13.0  
2               0.5     2.0   100.0   25.0  
3               0.5     2.4   155.5   27.0  
4               0.5     0.6     8.5   23.6  
...             ...     ...     ...    ...  
1027            1.0     2.2   800.0  165.3  
1028            1.0     2.0    44.5   11.1  
1029            1.0     1.1     7.7    6.4  
1030            1.0     2.4   809.1  140.5  
1031            1.0     2.4    53.6    9.3  

[1032 rows x 44 columns]

In [66]:
data[:500]

Number           Name    Type 1  Type 2  \
0         1      Bulbasaur     Grass  Poison   
1         2        Ivysaur     Grass  Poison   
2         3       Venusaur     Grass  Poison   
3         3  Mega Venusaur     Grass  Poison   
4         4     Charmander      Fire     NaN   
..      ...            ...       ...     ...   
495     415         Combee       Bug  Flying   
496     416      Vespiquen       Bug  Flying   
497     417      Pachirisu  Electric     NaN   
498     418         Buizel     Water     NaN   
499     419       Floatzel     Water     NaN   

                                 Abilities  HP  Att  Def  Spa  Spd  ...  \
0              ['Chlorophyll', 'Overgrow']  45   49   49   65   65  ...   
1              ['Chlorophyll', 'Overgrow']  60   62   63   80   80  ...   
2              ['Chlorophyll', 'Overgrow']  80   82   83  100  100  ...   
3                            ['Thick Fat']  80  100  123  122  120  ...   
4                 ['Blaze', 'Solar Power']  39   52   43   60   50  ...   
..                                     ...  ..  ...  ...  ...  ...  ...   
495             ['Honey Gather', 'Hustle']  30   30   42   30   42  ...   
496                ['Pressure', 'Unnerve']  70   80  102   80  102  ...   
497  ['Pickup', 'Run Away', 'Volt Absorb']  60   45   70   45   90  ...   
498           ['Swift Swim', 'Water Veil']  55   65   35   60   30  ...   
499           ['Swift Swim', 'Water Veil']  85  105   55   85   50  ...   

     Against Bug  Against Rock  Against Ghost  Against Dragon  Against Dark  \
0            1.0           1.0            1.0             1.0           1.0   
1            1.0           1.0            1.0             1.0           1.0   
2            1.0           1.0            1.0             1.0           1.0   
3            1.0           1.0            1.0             1.0           1.0   
4            0.5           2.0            1.0             1.0           1.0   
..           ...           ...            ...             ...           ...   
495          0.5           4.0            1.0             1.0           1.0   
496          0.5           4.0            1.0             1.0           1.0   
497          1.0           1.0            1.0             1.0           1.0   
498          1.0           1.0            1.0             1.0           1.0   
499          1.0           1.0            1.0             1.0           1.0   

    Against Steel  Against Fairy  Height  Weight   BMI  
0             1.0            0.5     0.7     6.9  14.1  
1             1.0            0.5     1.0    13.0  13.0  
2             1.0            0.5     2.0   100.0  25.0  
3             1.0            0.5     2.4   155.5  27.0  
4             0.5            0.5     0.6     8.5  23.6  
..            ...            ...     ...     ...   ...  
495           1.0            1.0     0.3     5.5  61.1  
496           1.0            1.0     1.2    38.5  26.7  
497           0.5            1.0     0.4     3.9  24.4  
498           0.5            1.0     0.7    29.5  60.2  
499           0.5            1.0     1.1    33.5  27.7  

[500 rows x 44 columns]

In [67]:
data

Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  Against Bug  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...          1.0   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...          1.0   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...          1.0   
3                   ['Thick Fat']   80  100  123  122  120  ...          1.0   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...          0.5   
...                           ...  ...  ...  ...  ...  ...  ...          ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...          1.0   
1028               ['Grim Neigh']  100   65   60  145   80  ...          0.5   
1029                  ['Unnerve']  100   80   80   80   80  ...          4.0   
1030                   ['As One']  100  165  150   85  130  ...          2.0   
1031                   ['As One']  100   85   80  165  100  ...          1.0   

      Against Rock  Against Ghost  Against Dragon  Against Dark Against Steel  \
0              1.0            1.0             1.0           1.0           1.0   
1              1.0            1.0             1.0           1.0           1.0   
2              1.0            1.0             1.0           1.0           1.0   
3              1.0            1.0             1.0           1.0           1.0   
4              2.0            1.0             1.0           1.0           0.5   
...            ...            ...             ...           ...           ...   
1027           2.0            1.0             1.0           1.0           2.0   
1028           1.0            2.0             1.0           2.0           1.0   
1029           1.0            2.0             1.0           2.0           1.0   
1030           2.0            2.0             1.0           2.0           2.0   
1031           1.0            4.0             1.0           4.0           1.0   

      Against Fairy  Height  Weight    BMI  
0               0.5     0.7     6.9   14.1  
1               0.5     1.0    13.0   13.0  
2               0.5     2.0   100.0   25.0  
3               0.5     2.4   155.5   27.0  
4               0.5     0.6     8.5   23.6  
...             ...     ...     ...    ...  
1027            1.0     2.2   800.0  165.3  
1028            1.0     2.0    44.5   11.1  
1029            1.0     1.1     7.7    6.4  
1030            1.0     2.4   809.1  140.5  
1031            1.0     2.4    53.6    9.3  

[1032 rows x 44 columns]

In [69]:
data[-300:]

Number                  Name   Type 1  Type 2                Abilities  \
732      633                 Deino     Dark  Dragon               ['Hustle']   
733      634              Zweilous     Dark  Dragon               ['Hustle']   
734      635             Hydreigon     Dark  Dragon             ['Levitate']   
735      636              Larvesta      Bug    Fire  ['Flame Body', 'Swarm']   
736      637             Volcarona      Bug    Fire  ['Flame Body', 'Swarm']   
...      ...                   ...      ...     ...                      ...   
1027     896             Glastrier      Ice     NaN       ['Chilling Neigh']   
1028     897             Spectrier    Ghost     NaN           ['Grim Neigh']   
1029     898               Calyrex  Psychic   Grass              ['Unnerve']   
1030     898     Calyrex Ice Rider  Psychic     Ice               ['As One']   
1031     898  Calyrex Shadow Rider  Psychic   Ghost               ['As One']   

       HP  Att  Def  Spa  Spd  ...  Against Bug  Against Rock  Against Ghost  \
732    52   65   50   45   50  ...          2.0           1.0            0.5   
733    72   85   70   65   70  ...          2.0           1.0            0.5   
734    92  105   90  125   90  ...          2.0           1.0            0.5   
735    55   85   55   50   55  ...          0.5           4.0            1.0   
736    85   60   65  135  105  ...          0.5           4.0            1.0   
...   ...  ...  ...  ...  ...  ...          ...           ...            ...   
1027  100  145  130   65  110  ...          1.0           2.0            1.0   
1028  100   65   60  145   80  ...          0.5           1.0            2.0   
1029  100   80   80   80   80  ...          4.0           1.0            2.0   
1030  100  165  150   85  130  ...          2.0           2.0            2.0   
1031  100   85   80  165  100  ...          1.0           1.0            4.0   

      Against Dragon  Against Dark Against Steel  Against Fairy  Height  \
732              2.0           0.5           1.0            4.0     0.8   
733              2.0           0.5           1.0            4.0     1.4   
734              2.0           0.5           1.0            4.0     1.8   
735              1.0           1.0           0.5            0.5     1.1   
736              1.0           1.0           0.5            0.5     1.6   
...              ...           ...           ...            ...     ...   
1027             1.0           1.0           2.0            1.0     2.2   
1028             1.0           2.0           1.0            1.0     2.0   
1029             1.0           2.0           1.0            1.0     1.1   
1030             1.0           2.0           2.0            1.0     2.4   
1031             1.0           4.0           1.0            1.0     2.4   

      Weight    BMI  
732     17.3   27.0  
733     50.0   25.5  
734    160.0   49.4  
735     28.8   23.8  
736     46.0   18.0  
...      ...    ...  
1027   800.0  165.3  
1028    44.5   11.1  
1029     7.7    6.4  
1030   809.1  140.5  
1031    53.6    9.3  

[300 rows x 44 columns]

In [71]:
data[:732:-1]

Number                  Name   Type 1    Type 2  \
1031     898  Calyrex Shadow Rider  Psychic     Ghost   
1030     898     Calyrex Ice Rider  Psychic       Ice   
1029     898               Calyrex  Psychic     Grass   
1028     897             Spectrier    Ghost       NaN   
1027     896             Glastrier      Ice       NaN   
...      ...                   ...      ...       ...   
737      638              Cobalion    Steel  Fighting   
736      637             Volcarona      Bug      Fire   
735      636              Larvesta      Bug      Fire   
734      635             Hydreigon     Dark    Dragon   
733      634              Zweilous     Dark    Dragon   

                    Abilities   HP  Att  Def  Spa  Spd  ...  Against Bug  \
1031               ['As One']  100   85   80  165  100  ...         1.00   
1030               ['As One']  100  165  150   85  130  ...         2.00   
1029              ['Unnerve']  100   80   80   80   80  ...         4.00   
1028           ['Grim Neigh']  100   65   60  145   80  ...         0.50   
1027       ['Chilling Neigh']  100  145  130   65  110  ...         1.00   
...                       ...  ...  ...  ...  ...  ...  ...          ...   
737             ['Justified']   91   90  129   90   72  ...         0.25   
736   ['Flame Body', 'Swarm']   85   60   65  135  105  ...         0.50   
735   ['Flame Body', 'Swarm']   55   85   55   50   55  ...         0.50   
734              ['Levitate']   92  105   90  125   90  ...         2.00   
733                ['Hustle']   72   85   70   65   70  ...         2.00   

      Against Rock  Against Ghost  Against Dragon  Against Dark Against Steel  \
1031          1.00            4.0             1.0           4.0           1.0   
1030          2.00            2.0             1.0           2.0           2.0   
1029          1.00            2.0             1.0           2.0           1.0   
1028          1.00            2.0             1.0           2.0           1.0   
1027          2.00            1.0             1.0           1.0           2.0   
...            ...            ...             ...           ...           ...   
737           0.25            1.0             0.5           0.5           0.5   
736           4.00            1.0             1.0           1.0           0.5   
735           4.00            1.0             1.0           1.0           0.5   
734           1.00            0.5             2.0           0.5           1.0   
733           1.00            0.5             2.0           0.5           1.0   

      Against Fairy  Height  Weight    BMI  
1031            1.0     2.4    53.6    9.3  
1030            1.0     2.4   809.1  140.5  
1029            1.0     1.1     7.7    6.4  
1028            1.0     2.0    44.5   11.1  
1027            1.0     2.2   800.0  165.3  
...             ...     ...     ...    ...  
737             1.0     2.1   250.0   56.7  
736             0.5     1.6    46.0   18.0  
735             0.5     1.1    28.8   23.8  
734             4.0     1.8   160.0   49.4  
733             4.0     1.4    50.0   25.5  

[299 rows x 44 columns]

In [72]:
data.columns

Index(['Number', 'Name', 'Type 1', 'Type 2', 'Abilities', 'HP', 'Att', 'Def',
       'Spa', 'Spd', 'Spe', 'BST', 'Mean', 'Standard Deviation', 'Generation',
       'Experience type', 'Experience to level 100', 'Final Evolution',
       'Catch Rate', 'Legendary', 'Mega Evolution', 'Alolan Form',
       'Galarian Form', 'Against Normal', 'Against Fire', 'Against Water',
       'Against Electric', 'Against Grass', 'Against Ice', 'Against Fighting',
       'Against Poison', 'Against Ground', 'Against Flying', 'Against Psychic',
       'Against Bug', 'Against Rock', 'Against Ghost', 'Against Dragon',
       'Against Dark', 'Against Steel', 'Against Fairy', 'Height', 'Weight',
       'BMI'],
      dtype='object')

In [74]:
data.iloc[::,::] #index of location

Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  Against Bug  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...          1.0   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...          1.0   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...          1.0   
3                   ['Thick Fat']   80  100  123  122  120  ...          1.0   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...          0.5   
...                           ...  ...  ...  ...  ...  ...  ...          ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...          1.0   
1028               ['Grim Neigh']  100   65   60  145   80  ...          0.5   
1029                  ['Unnerve']  100   80   80   80   80  ...          4.0   
1030                   ['As One']  100  165  150   85  130  ...          2.0   
1031                   ['As One']  100   85   80  165  100  ...          1.0   

      Against Rock  Against Ghost  Against Dragon  Against Dark Against Steel  \
0              1.0            1.0             1.0           1.0           1.0   
1              1.0            1.0             1.0           1.0           1.0   
2              1.0            1.0             1.0           1.0           1.0   
3              1.0            1.0             1.0           1.0           1.0   
4              2.0            1.0             1.0           1.0           0.5   
...            ...            ...             ...           ...           ...   
1027           2.0            1.0             1.0           1.0           2.0   
1028           1.0            2.0             1.0           2.0           1.0   
1029           1.0            2.0             1.0           2.0           1.0   
1030           2.0            2.0             1.0           2.0           2.0   
1031           1.0            4.0             1.0           4.0           1.0   

      Against Fairy  Height  Weight    BMI  
0               0.5     0.7     6.9   14.1  
1               0.5     1.0    13.0   13.0  
2               0.5     2.0   100.0   25.0  
3               0.5     2.4   155.5   27.0  
4               0.5     0.6     8.5   23.6  
...             ...     ...     ...    ...  
1027            1.0     2.2   800.0  165.3  
1028            1.0     2.0    44.5   11.1  
1029            1.0     1.1     7.7    6.4  
1030            1.0     2.4   809.1  140.5  
1031            1.0     2.4    53.6    9.3  

[1032 rows x 44 columns]

In [76]:
data.iloc[::,:-1]

Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...   
3                   ['Thick Fat']   80  100  123  122  120  ...   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...   
...                           ...  ...  ...  ...  ...  ...  ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...   
1028               ['Grim Neigh']  100   65   60  145   80  ...   
1029                  ['Unnerve']  100   80   80   80   80  ...   
1030                   ['As One']  100  165  150   85  130  ...   
1031                   ['As One']  100   85   80  165  100  ...   

      Against Psychic  Against Bug  Against Rock  Against Ghost  \
0                 2.0          1.0           1.0            1.0   
1                 2.0          1.0           1.0            1.0   
2                 2.0          1.0           1.0            1.0   
3                 2.0          1.0           1.0            1.0   
4                 1.0          0.5           2.0            1.0   
...               ...          ...           ...            ...   
1027              1.0          1.0           2.0            1.0   
1028              1.0          0.5           1.0            2.0   
1029              0.5          4.0           1.0            2.0   
1030              0.5          2.0           2.0            2.0   
1031              0.5          1.0           1.0            4.0   

      Against Dragon Against Dark  Against Steel  Against Fairy  Height  \
0                1.0          1.0            1.0            0.5     0.7   
1                1.0          1.0            1.0            0.5     1.0   
2                1.0          1.0            1.0            0.5     2.0   
3                1.0          1.0            1.0            0.5     2.4   
4                1.0          1.0            0.5            0.5     0.6   
...              ...          ...            ...            ...     ...   
1027             1.0          1.0            2.0            1.0     2.2   
1028             1.0          2.0            1.0            1.0     2.0   
1029             1.0          2.0            1.0            1.0     1.1   
1030             1.0          2.0            2.0            1.0     2.4   
1031             1.0          4.0            1.0            1.0     2.4   

      Weight  
0        6.9  
1       13.0  
2      100.0  
3      155.5  
4        8.5  
...      ...  
1027   800.0  
1028    44.5  
1029     7.7  
1030   809.1  
1031    53.6  

[1032 rows x 43 columns]

In [79]:
data.iloc[:,2:]

Type 1  Type 2                    Abilities   HP  Att  Def  Spa  Spd  \
0       Grass  Poison  ['Chlorophyll', 'Overgrow']   45   49   49   65   65   
1       Grass  Poison  ['Chlorophyll', 'Overgrow']   60   62   63   80   80   
2       Grass  Poison  ['Chlorophyll', 'Overgrow']   80   82   83  100  100   
3       Grass  Poison                ['Thick Fat']   80  100  123  122  120   
4        Fire     NaN     ['Blaze', 'Solar Power']   39   52   43   60   50   
...       ...     ...                          ...  ...  ...  ...  ...  ...   
1027      Ice     NaN           ['Chilling Neigh']  100  145  130   65  110   
1028    Ghost     NaN               ['Grim Neigh']  100   65   60  145   80   
1029  Psychic   Grass                  ['Unnerve']  100   80   80   80   80   
1030  Psychic     Ice                   ['As One']  100  165  150   85  130   
1031  Psychic   Ghost                   ['As One']  100   85   80  165  100   

      Spe  BST  ...  Against Bug  Against Rock  Against Ghost Against Dragon  \
0      45  318  ...          1.0           1.0            1.0            1.0   
1      60  405  ...          1.0           1.0            1.0            1.0   
2      80  525  ...          1.0           1.0            1.0            1.0   
3      80  625  ...          1.0           1.0            1.0            1.0   
4      65  309  ...          0.5           2.0            1.0            1.0   
...   ...  ...  ...          ...           ...            ...            ...   
1027   30  580  ...          1.0           2.0            1.0            1.0   
1028  130  580  ...          0.5           1.0            2.0            1.0   
1029   80  500  ...          4.0           1.0            2.0            1.0   
1030   50  680  ...          2.0           2.0            2.0            1.0   
1031  150  680  ...          1.0           1.0            4.0            1.0   

      Against Dark  Against Steel  Against Fairy  Height  Weight    BMI  
0              1.0            1.0            0.5     0.7     6.9   14.1  
1              1.0            1.0            0.5     1.0    13.0   13.0  
2              1.0            1.0            0.5     2.0   100.0   25.0  
3              1.0            1.0            0.5     2.4   155.5   27.0  
4              1.0            0.5            0.5     0.6     8.5   23.6  
...            ...            ...            ...     ...     ...    ...  
1027           1.0            2.0            1.0     2.2   800.0  165.3  
1028           2.0            1.0            1.0     2.0    44.5   11.1  
1029           2.0            1.0            1.0     1.1     7.7    6.4  
1030           2.0            2.0            1.0     2.4   809.1  140.5  
1031           4.0            1.0            1.0     2.4    53.6    9.3  

[1032 rows x 42 columns]

In [81]:
data.columns

Index(['Number', 'Name', 'Type 1', 'Type 2', 'Abilities', 'HP', 'Att', 'Def',
       'Spa', 'Spd', 'Spe', 'BST', 'Mean', 'Standard Deviation', 'Generation',
       'Experience type', 'Experience to level 100', 'Final Evolution',
       'Catch Rate', 'Legendary', 'Mega Evolution', 'Alolan Form',
       'Galarian Form', 'Against Normal', 'Against Fire', 'Against Water',
       'Against Electric', 'Against Grass', 'Against Ice', 'Against Fighting',
       'Against Poison', 'Against Ground', 'Against Flying', 'Against Psychic',
       'Against Bug', 'Against Rock', 'Against Ghost', 'Against Dragon',
       'Against Dark', 'Against Steel', 'Against Fairy', 'Height', 'Weight',
       'BMI'],
      dtype='object')

In [82]:
data['BMI']

0        14.1
1        13.0
2        25.0
3        27.0
4        23.6
        ...  
1027    165.3
1028     11.1
1029      6.4
1030    140.5
1031      9.3
Name: BMI, Length: 1032, dtype: float64

In [83]:
data.iloc[:,:-1]



Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...   
3                   ['Thick Fat']   80  100  123  122  120  ...   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...   
...                           ...  ...  ...  ...  ...  ...  ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...   
1028               ['Grim Neigh']  100   65   60  145   80  ...   
1029                  ['Unnerve']  100   80   80   80   80  ...   
1030                   ['As One']  100  165  150   85  130  ...   
1031                   ['As One']  100   85   80  165  100  ...   

      Against Psychic  Against Bug  Against Rock  Against Ghost  \
0                 2.0          1.0           1.0            1.0   
1                 2.0          1.0           1.0            1.0   
2                 2.0          1.0           1.0            1.0   
3                 2.0          1.0           1.0            1.0   
4                 1.0          0.5           2.0            1.0   
...               ...          ...           ...            ...   
1027              1.0          1.0           2.0            1.0   
1028              1.0          0.5           1.0            2.0   
1029              0.5          4.0           1.0            2.0   
1030              0.5          2.0           2.0            2.0   
1031              0.5          1.0           1.0            4.0   

      Against Dragon Against Dark  Against Steel  Against Fairy  Height  \
0                1.0          1.0            1.0            0.5     0.7   
1                1.0          1.0            1.0            0.5     1.0   
2                1.0          1.0            1.0            0.5     2.0   
3                1.0          1.0            1.0            0.5     2.4   
4                1.0          1.0            0.5            0.5     0.6   
...              ...          ...            ...            ...     ...   
1027             1.0          1.0            2.0            1.0     2.2   
1028             1.0          2.0            1.0            1.0     2.0   
1029             1.0          2.0            1.0            1.0     1.1   
1030             1.0          2.0            2.0            1.0     2.4   
1031             1.0          4.0            1.0            1.0     2.4   

      Weight  
0        6.9  
1       13.0  
2      100.0  
3      155.5  
4        8.5  
...      ...  
1027   800.0  
1028    44.5  
1029     7.7  
1030   809.1  
1031    53.6  

[1032 rows x 43 columns]

In [84]:
data.drop('BMI',axis=1)



Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...   
3                   ['Thick Fat']   80  100  123  122  120  ...   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...   
...                           ...  ...  ...  ...  ...  ...  ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...   
1028               ['Grim Neigh']  100   65   60  145   80  ...   
1029                  ['Unnerve']  100   80   80   80   80  ...   
1030                   ['As One']  100  165  150   85  130  ...   
1031                   ['As One']  100   85   80  165  100  ...   

      Against Psychic  Against Bug  Against Rock  Against Ghost  \
0                 2.0          1.0           1.0            1.0   
1                 2.0          1.0           1.0            1.0   
2                 2.0          1.0           1.0            1.0   
3                 2.0          1.0           1.0            1.0   
4                 1.0          0.5           2.0            1.0   
...               ...          ...           ...            ...   
1027              1.0          1.0           2.0            1.0   
1028              1.0          0.5           1.0            2.0   
1029              0.5          4.0           1.0            2.0   
1030              0.5          2.0           2.0            2.0   
1031              0.5          1.0           1.0            4.0   

      Against Dragon Against Dark  Against Steel  Against Fairy  Height  \
0                1.0          1.0            1.0            0.5     0.7   
1                1.0          1.0            1.0            0.5     1.0   
2                1.0          1.0            1.0            0.5     2.0   
3                1.0          1.0            1.0            0.5     2.4   
4                1.0          1.0            0.5            0.5     0.6   
...              ...          ...            ...            ...     ...   
1027             1.0          1.0            2.0            1.0     2.2   
1028             1.0          2.0            1.0            1.0     2.0   
1029             1.0          2.0            1.0            1.0     1.1   
1030             1.0          2.0            2.0            1.0     2.4   
1031             1.0          4.0            1.0            1.0     2.4   

      Weight  
0        6.9  
1       13.0  
2      100.0  
3      155.5  
4        8.5  
...      ...  
1027   800.0  
1028    44.5  
1029     7.7  
1030   809.1  
1031    53.6  

[1032 rows x 43 columns]

In [86]:
data.drop(columns=['Height','Weight'],axis=1)

Number                  Name   Type 1  Type 2  \
0          1             Bulbasaur    Grass  Poison   
1          2               Ivysaur    Grass  Poison   
2          3              Venusaur    Grass  Poison   
3          3         Mega Venusaur    Grass  Poison   
4          4            Charmander     Fire     NaN   
...      ...                   ...      ...     ...   
1027     896             Glastrier      Ice     NaN   
1028     897             Spectrier    Ghost     NaN   
1029     898               Calyrex  Psychic   Grass   
1030     898     Calyrex Ice Rider  Psychic     Ice   
1031     898  Calyrex Shadow Rider  Psychic   Ghost   

                        Abilities   HP  Att  Def  Spa  Spd  ...  \
0     ['Chlorophyll', 'Overgrow']   45   49   49   65   65  ...   
1     ['Chlorophyll', 'Overgrow']   60   62   63   80   80  ...   
2     ['Chlorophyll', 'Overgrow']   80   82   83  100  100  ...   
3                   ['Thick Fat']   80  100  123  122  120  ...   
4        ['Blaze', 'Solar Power']   39   52   43   60   50  ...   
...                           ...  ...  ...  ...  ...  ...  ...   
1027           ['Chilling Neigh']  100  145  130   65  110  ...   
1028               ['Grim Neigh']  100   65   60  145   80  ...   
1029                  ['Unnerve']  100   80   80   80   80  ...   
1030                   ['As One']  100  165  150   85  130  ...   
1031                   ['As One']  100   85   80  165  100  ...   

      Against Flying  Against Psychic  Against Bug  Against Rock  \
0                2.0              2.0          1.0           1.0   
1                2.0              2.0          1.0           1.0   
2                2.0              2.0          1.0           1.0   
3                2.0              2.0          1.0           1.0   
4                1.0              1.0          0.5           2.0   
...              ...              ...          ...           ...   
1027             1.0              1.0          1.0           2.0   
1028             1.0              1.0          0.5           1.0   
1029             2.0              0.5          4.0           1.0   
1030             1.0              0.5          2.0           2.0   
1031             1.0              0.5          1.0           1.0   

      Against Ghost Against Dragon  Against Dark  Against Steel  \
0               1.0            1.0           1.0            1.0   
1               1.0            1.0           1.0            1.0   
2               1.0            1.0           1.0            1.0   
3               1.0            1.0           1.0            1.0   
4               1.0            1.0           1.0            0.5   
...             ...            ...           ...            ...   
1027            1.0            1.0           1.0            2.0   
1028            2.0            1.0           2.0            1.0   
1029            2.0            1.0           2.0            1.0   
1030            2.0            1.0           2.0            2.0   
1031            4.0            1.0           4.0            1.0   

      Against Fairy    BMI  
0               0.5   14.1  
1               0.5   13.0  
2               0.5   25.0  
3               0.5   27.0  
4               0.5   23.6  
...             ...    ...  
1027            1.0  165.3  
1028            1.0   11.1  
1029            1.0    6.4  
1030            1.0  140.5  
1031            1.0    9.3  

[1032 rows x 42 columns]

In [88]:
data[['Height','Weight']]

Height  Weight
0        0.7     6.9
1        1.0    13.0
2        2.0   100.0
3        2.4   155.5
4        0.6     8.5
...      ...     ...
1027     2.2   800.0
1028     2.0    44.5
1029     1.1     7.7
1030     2.4   809.1
1031     2.4    53.6

[1032 rows x 2 columns]

In [89]:
data.columns

Index(['Number', 'Name', 'Type 1', 'Type 2', 'Abilities', 'HP', 'Att', 'Def',
       'Spa', 'Spd', 'Spe', 'BST', 'Mean', 'Standard Deviation', 'Generation',
       'Experience type', 'Experience to level 100', 'Final Evolution',
       'Catch Rate', 'Legendary', 'Mega Evolution', 'Alolan Form',
       'Galarian Form', 'Against Normal', 'Against Fire', 'Against Water',
       'Against Electric', 'Against Grass', 'Against Ice', 'Against Fighting',
       'Against Poison', 'Against Ground', 'Against Flying', 'Against Psychic',
       'Against Bug', 'Against Rock', 'Against Ghost', 'Against Dragon',
       'Against Dark', 'Against Steel', 'Against Fairy', 'Height', 'Weight',
       'BMI'],
      dtype='object')

In [90]:
#col 10-20
#col Final Evoluation, Against Fairy
#col remove first two col, last two col

BMI
0      14.1
1      13.0
2      25.0
3      27.0
4      23.6
...     ...
1027  165.3
1028   11.1
1029    6.4
1030  140.5
1031    9.3

[1032 rows x 1 columns]