In [1]:
import pandas as pd
df=pd.read_csv('dataset/All_Pokemon.csv')
df.head()

Number           Name Type 1  Type 2                    Abilities  HP  \
0       1      Bulbasaur  Grass  Poison  ['Chlorophyll', 'Overgrow']  45   
1       2        Ivysaur  Grass  Poison  ['Chlorophyll', 'Overgrow']  60   
2       3       Venusaur  Grass  Poison  ['Chlorophyll', 'Overgrow']  80   
3       3  Mega Venusaur  Grass  Poison                ['Thick Fat']  80   
4       4     Charmander   Fire     NaN     ['Blaze', 'Solar Power']  39   

     Att  Def  Spa    Spd  ...  Against Bug  Against Rock  Against Ghost  \
0   49.0   49   65   65.0  ...          1.0           1.0            1.0   
1    NaN   63   80   80.0  ...          1.0           1.0            1.0   
2   82.0   83  100    NaN  ...          1.0           1.0            1.0   
3  100.0  123  122  120.0  ...          1.0           1.0            1.0   
4   52.0   43   60   50.0  ...          0.5           2.0            1.0   

   Against Dragon  Against Dark Against Steel  Against Fairy  Height  Weight  \
0             1.0           1.0           1.0            0.5     0.7     6.9   
1             1.0           1.0           1.0            0.5     1.0    13.0   
2             1.0           NaN           1.0            0.5     2.0   100.0   
3             1.0           1.0           1.0            0.5     2.4   155.5   
4             1.0           1.0           0.5            0.5     0.6     8.5   

    BMI  
0  14.1  
1  13.0  
2  25.0  
3  27.0  
4  23.6  

[5 rows x 44 columns]

In [2]:
df.dropna(inplace=True)

In [3]:
#Scaling
df.dtypes

Number                       int64
Name                        object
Type 1                      object
Type 2                      object
Abilities                   object
HP                           int64
Att                        float64
Def                          int64
Spa                          int64
Spd                        float64
Spe                          int64
BST                          int64
Mean                       float64
Standard Deviation         float64
Generation                 float64
Experience type             object
Experience to level 100      int64
Final Evolution            float64
Catch Rate                   int64
Legendary                  float64
Mega Evolution             float64
Alolan Form                float64
Galarian Form              float64
Against Normal             float64
Against Fire               float64
Against Water              float64
Against Electric           float64
Against Grass              float64
Against Ice         

In [6]:
df.select_dtypes(include='object')

Name    Type 1  Type 2  \
0                       Bulbasaur     Grass  Poison   
3                   Mega Venusaur     Grass  Poison   
6                       Charizard      Fire  Flying   
7                Mega Charizard Y      Fire  Flying   
8                Mega Charizard X      Fire  Dragon   
...                           ...       ...     ...   
1023  Urshifu Single Strike Style  Fighting    Dark   
1024                       Zarude      Dark   Grass   
1029                      Calyrex   Psychic   Grass   
1030            Calyrex Ice Rider   Psychic     Ice   
1031         Calyrex Shadow Rider   Psychic   Ghost   

                        Abilities Experience type  
0     ['Chlorophyll', 'Overgrow']     Medium Slow  
3                   ['Thick Fat']     Medium Slow  
6        ['Blaze', 'Solar Power']     Medium Slow  
7                     ['Drought']     Medium Slow  
8                 ['Tough Claws']     Medium Slow  
...                           ...             ...  
1023              ['Unseen Fist']            Slow  
1024               ['Leaf Guard']            Slow  
1029                  ['Unnerve']            Slow  
1030                   ['As One']            Slow  
1031                   ['As One']            Slow  

[546 rows x 5 columns]

In [7]:
df.select_dtypes(exclude='object').columns

Index(['Number', 'HP', 'Att', 'Def', 'Spa', 'Spd', 'Spe', 'BST', 'Mean',
       'Standard Deviation', 'Generation', 'Experience to level 100',
       'Final Evolution', 'Catch Rate', 'Legendary', 'Mega Evolution',
       'Alolan Form', 'Galarian Form', 'Against Normal', 'Against Fire',
       'Against Water', 'Against Electric', 'Against Grass', 'Against Ice',
       'Against Fighting', 'Against Poison', 'Against Ground',
       'Against Flying', 'Against Psychic', 'Against Bug', 'Against Rock',
       'Against Ghost', 'Against Dragon', 'Against Dark', 'Against Steel',
       'Against Fairy', 'Height', 'Weight', 'BMI'],
      dtype='object')

In [8]:
df.select_dtypes(exclude='object').head()

Number  HP    Att  Def  Spa    Spd  Spe  BST        Mean  \
0       1  45   49.0   49   65   65.0   45  318   53.000000   
3       3  80  100.0  123  122  120.0   80  625  104.166667   
6       6  78   84.0   78  109   85.0  100  534   89.000000   
7       6  78  104.0   78  159  115.0  100  634  105.666667   
8       6  78  130.0  111  130   85.0  100  634  105.666667   

   Standard Deviation  ...  Against Bug  Against Rock  Against Ghost  \
0            8.640988  ...         1.00           1.0            1.0   
3           18.747592  ...         1.00           1.0            1.0   
6           11.575837  ...         0.25           4.0            1.0   
7           27.378012  ...         0.25           4.0            1.0   
8           20.154955  ...         0.50           2.0            1.0   

   Against Dragon  Against Dark  Against Steel  Against Fairy  Height  Weight  \
0             1.0           1.0            1.0            0.5     0.7     6.9   
3             1.0           1.0            1.0            0.5     2.4   155.5   
6             1.0           1.0            0.5            0.5     1.7    90.5   
7             1.0           1.0            0.5            0.5     1.7   100.5   
8             2.0           1.0            0.5            1.0     1.7   110.5   

    BMI  
0  14.1  
3  27.0  
6  31.3  
7  34.8  
8  38.2  

[5 rows x 39 columns]

In [10]:
"""
#alternative way
from sklearn import preprocessing
std=preprocessing.StandardScaler()
"""

from sklearn.preprocessing import StandardScaler
std=StandardScaler() #instance
value=std.fit_transform(df[['HP','Att']])
value


array([[-1.09011414, -1.07525032],
       [ 0.3228051 ,  0.45565368],
       [ 0.24206685, -0.02462993],
       ...,
       [ 1.13018751, -0.14470083],
       [ 1.13018751,  2.40680582],
       [ 1.13018751,  0.0053878 ]])

In [12]:
value=std.fit_transform(df['Spd'].values.reshape(-1,1))
value

array([[-4.04934503e-01],
       [ 1.59707128e+00],
       [ 3.23067600e-01],
       [ 1.41507075e+00],
       [ 3.23067600e-01],
       [ 1.41067074e-01],
       [-2.04293924e+00],
       [-1.86093871e+00],
       [ 1.41067074e-01],
       [ 1.41067074e-01],
       [-1.49693766e+00],
       [-9.50936080e-01],
       [-2.22933977e-01],
       [ 1.41067074e-01],
       [-1.49693766e+00],
       [ 1.41067074e-01],
       [-1.64253808e+00],
       [-5.50534924e-01],
       [ 3.23067600e-01],
       [-1.49693766e+00],
       [-4.04934503e-01],
       [ 3.23067600e-01],
       [-4.09334516e-02],
       [ 8.69069177e-01],
       [-1.86093871e+00],
       [-9.50936080e-01],
       [-1.31493713e+00],
       [-4.09334516e-02],
       [-4.04934503e-01],
       [-4.09334516e-02],
       [ 5.05068126e-01],
       [-7.68935555e-01],
       [ 1.41067074e-01],
       [-7.68935555e-01],
       [-4.09334516e-02],
       [-1.13293661e+00],
       [-2.22933977e-01],
       [ 5.05068126e-01],
       [-1.6

In [13]:
df[['HP','Att']]

HP    Att
0      45   49.0
3      80  100.0
6      78   84.0
7      78  104.0
8      78  130.0
...   ...    ...
1023  100  130.0
1024  105  120.0
1029  100   80.0
1030  100  165.0
1031  100   85.0

[546 rows x 2 columns]

In [14]:
#Zscore normalization
# no library , no API
#scratch
#zscore= ( x- mean) / standard deviation

def zscore(df):  #function
    for col in df.columns:
        df[col]=(df[col]-df[col].mean())/df[col].std()
    return df

value=zscore(df[['HP','Att']])
value

C:\Users\Dell\AppData\Local\Temp\ipykernel_13944\584521716.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=(df[col]-df[col].mean())/df[col].std()


HP       Att
0    -1.089115 -1.074265
3     0.322509  0.455236
6     0.241845 -0.024607
7     0.241845  0.575197
8     0.241845  1.354943
...        ...       ...
1023  1.129152  1.354943
1024  1.330813  1.055041
1029  1.129152 -0.144568
1030  1.129152  2.404601
1031  1.129152  0.005383

[546 rows x 2 columns]

In [21]:
#Scaling
#MinMaxScaler
#Maximum Absolute scaler

from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler(feature_range=(3, 8))#default 0-1
value=mm.fit_transform(df[['HP','Att']])
value

array([[3.99099099, 4.08333333],
       [4.77927928, 5.5       ],
       [4.73423423, 5.05555556],
       ...,
       [5.22972973, 4.94444444],
       [5.22972973, 7.30555556],
       [5.22972973, 5.08333333]])

In [23]:
from sklearn.preprocessing import MaxAbsScaler
ab=MaxAbsScaler()
value=ab.fit_transform(df[['Att','Spd']])
value

array([[0.25789474, 0.2826087 ],
       [0.52631579, 0.52173913],
       [0.44210526, 0.36956522],
       ...,
       [0.42105263, 0.34782609],
       [0.86842105, 0.56521739],
       [0.44736842, 0.43478261]])

In [25]:
#Feature selection / extraction  <-- featuer engineering
house=pd.read_csv('dataset/AmesHousing.csv')
house.head()

Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave   
1      2  526350040           20        RH          80.0     11622   Pave   
2      3  526351010           20        RL          81.0     14267   Pave   
3      4  526353030           20        RL          93.0     11160   Pave   
4      5  527105010           60        RL          74.0     13830   Pave   

  Alley Lot Shape Land Contour  ... Pool Area Pool QC  Fence Misc Feature  \
0   NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
1   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
2   NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
3   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
4   NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN   

  Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice  
0        0       5    2010       WD           Normal     215000  
1        0       6    2010       WD           Normal     105000  
2    12500       6    2010       WD           Normal     172000  
3        0       4    2010       WD           Normal     244000  
4        0       3    2010       WD           Normal     189900  

[5 rows x 82 columns]

In [26]:
house.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
      

In [ ]:
data.drop(columns=['...','...'])

data[['Misc Feature','Bsmt Expoture']]

In [28]:
#Feature Extraction / Selection

# Filter
# Extraction with Model - ML algorithm

#Filter
cor_val=house.corr() # -1 1 - 1 means totally dependencies  + ->same direction -> opposite direction
cor_val

C:\Users\Dell\AppData\Local\Temp\ipykernel_13944\3117974771.py:7: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cor_val=house.corr()


Order       PID  MS SubClass  Lot Frontage  Lot Area  \
Order            1.000000  0.173593     0.011797     -0.007034  0.031354   
PID              0.173593  1.000000    -0.001281     -0.096918  0.034868   
MS SubClass      0.011797 -0.001281     1.000000     -0.420135 -0.204613   
Lot Frontage    -0.007034 -0.096918    -0.420135      1.000000  0.491313   
Lot Area         0.031354  0.034868    -0.204613      0.491313  1.000000   
Overall Qual    -0.048500 -0.263147     0.039419      0.212042  0.097188   
Overall Cond    -0.011054  0.104451    -0.067349     -0.074448 -0.034759   
Year Built      -0.052319 -0.343388     0.036579      0.121562  0.023258   
Year Remod/Add  -0.075566 -0.157111     0.043397      0.091712  0.021682   
Mas Vnr Area    -0.030907 -0.229283     0.002730      0.222407  0.126830   
BsmtFin SF 1    -0.032321 -0.098375    -0.060075      0.215583  0.191555   
BsmtFin SF 2    -0.002773 -0.001145    -0.070946      0.045999  0.083150   
Bsmt Unf SF      0.005780 -0.087707    -0.130421      0.116743  0.023658   
Total Bsmt SF   -0.028719 -0.189642    -0.219445      0.353773  0.253589   
1st Flr SF      -0.013201 -0.141902    -0.247828      0.457391  0.332235   
2nd Flr SF      -0.000417 -0.003289     0.304237      0.029187  0.032996   
Low Qual Fin SF  0.013589  0.056940     0.025765      0.005249  0.000812   
Gr Liv Area     -0.009342 -0.107579     0.068061      0.383822  0.285599   
Bsmt Full Bath  -0.042539 -0.037759     0.013701      0.108915  0.125877   
Bsmt Half Bath   0.024978  0.004328    -0.003329     -0.024724  0.026903   
Full Bath       -0.044985 -0.171431     0.134631      0.184521  0.127433   
Half Bath       -0.039749 -0.166636     0.175879      0.041880  0.035497   
Bedroom AbvGr    0.015424  0.006345    -0.019208      0.240442  0.136569   
Kitchen AbvGr   -0.017685  0.076470     0.257698      0.005407 -0.020301   
TotRms AbvGrd    0.002612 -0.068981     0.031898      0.353137  0.216597   
Fireplaces      -0.019156 -0.108056    -0.049955      0.257255  0.256989   
Garage Yr Blt   -0.051160 -0.256829     0.088754      0.076306 -0.008952   
Garage Cars     -0.036185 -0.237484    -0.045883      0.308706  0.179512   
Garage Area     -0.035435 -0.210606    -0.103239      0.358505  0.212822   
Wood Deck SF    -0.011292 -0.051135    -0.017310      0.120084  0.157212   
Open Porch SF    0.016355 -0.071311    -0.014823      0.163040  0.103760   
Enclosed Porch   0.027908  0.162519    -0.022866      0.012758  0.021868   
3Ssn Porch      -0.024975 -0.024894    -0.037956      0.028564  0.016243   
Screen Porch     0.004307 -0.025735    -0.050614      0.076666  0.055044   
Pool Area        0.052518 -0.002845    -0.003434      0.173947  0.093775   
Misc Val        -0.006083 -0.008260    -0.029254      0.044476  0.069188   
Mo Sold          0.133365 -0.050455     0.000350      0.011085  0.003859   
Yr Sold         -0.975993  0.009579    -0.017905     -0.007547 -0.023085   
SalePrice       -0.031408 -0.246521    -0.085092      0.357318  0.266549   

                 Overall Qual  Overall Cond  Year Built  Year Remod/Add  \
Order               -0.048500     -0.011054   -0.052319       -0.075566   
PID                 -0.263147      0.104451   -0.343388       -0.157111   
MS SubClass          0.039419     -0.067349    0.036579        0.043397   
Lot Frontage         0.212042     -0.074448    0.121562        0.091712   
Lot Area             0.097188     -0.034759    0.023258        0.021682   
Overall Qual         1.000000     -0.094812    0.597027        0.569609   
Overall Cond        -0.094812      1.000000   -0.368773        0.047680   
Year Built           0.597027     -0.368773    1.000000        0.612095   
Year Remod/Add       0.569609      0.047680    0.612095        1.000000   
Mas Vnr Area         0.429418     -0.135340    0.313292        0.196928   
BsmtFin SF 1         0.284118     -0.050935    0.279870        0.151790   
BsmtFin SF 2        -0.041287      0.041134   -0.027415       -0.062129   
Bsmt

In [32]:
target_value=abs(cor_val['SalePrice'])
target_value[target_value>0.5] #threshold value

#diabteite
#least / most relationship with Outcome

Overall Qual      0.799262
Year Built        0.558426
Year Remod/Add    0.532974
Mas Vnr Area      0.508285
Total Bsmt SF     0.632280
1st Flr SF        0.621676
Gr Liv Area       0.706780
Full Bath         0.545604
Garage Yr Blt     0.526965
Garage Cars       0.647877
Garage Area       0.640401
SalePrice         1.000000
Name: SalePrice, dtype: float64

In [44]:
#Feature selection -> not null, only numeric
house=pd.read_csv('dataset/AmesHousing.csv')
house.isnull().sum()
house=house.drop('Lot Frontage',axis=1)
house.isnull().sum()

Order             0
PID               0
MS SubClass       0
MS Zoning         0
Lot Area          0
                 ..
Mo Sold           0
Yr Sold           0
Sale Type         0
Sale Condition    0
SalePrice         0
Length: 81, dtype: int64

In [45]:
len(house)

2930

In [48]:
cate_house=house.select_dtypes(include='object')
cate_house.head()
cate_house.isnull().sum()

MS Zoning            0
Street               0
Alley             2732
Lot Shape            0
Land Contour         0
Utilities            0
Lot Config           0
Land Slope           0
Neighborhood         0
Condition 1          0
Condition 2          0
Bldg Type            0
House Style          0
Roof Style           0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
Mas Vnr Type        23
Exter Qual           0
Exter Cond           0
Foundation           0
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin Type 2      81
Heating              0
Heating QC           0
Central Air          0
Electrical           1
Kitchen Qual         0
Functional           0
Fireplace Qu      1422
Garage Type        157
Garage Finish      159
Garage Qual        159
Garage Cond        159
Paved Drive          0
Pool QC           2917
Fence             2358
Misc Feature      2824
Sale Type            0
Sale Condition       0
dtype: int6

In [50]:
house=house.drop(columns=['Pool QC','Fence','Misc Feature','Alley'],axis=1)

In [52]:
new_house=house.dropna()
new_house=new_house.select_dtypes(exclude='object')
new_house.head()

Order        PID  MS SubClass  Lot Area  Overall Qual  Overall Cond  \
0      1  526301100           20     31770             6             5   
3      4  526353030           20     11160             7             5   
4      5  527105010           60     13830             5             5   
5      6  527105030           60      9978             6             6   
8      9  527146030          120      5389             8             5   

   Year Built  Year Remod/Add  Mas Vnr Area  BsmtFin SF 1  ...  Wood Deck SF  \
0        1960            1960         112.0         639.0  ...           210   
3        1968            1968           0.0        1065.0  ...             0   
4        1997            1998           0.0         791.0  ...           212   
5        1998            1998          20.0         602.0  ...           360   
8        1995            1996           0.0        1180.0  ...           237   

   Open Porch SF  Enclosed Porch  3Ssn Porch  Screen Porch  Pool Area  \
0             62               0           0             0          0   
3              0               0           0             0          0   
4             34               0           0             0          0   
5             36               0           0             0          0   
8            152               0           0             0          0   

   Misc Val  Mo Sold  Yr Sold  SalePrice  
0         0        5     2010     215000  
3         0        4     2010     244000  
4         0        3     2010     189900  
5         0        6     2010     195500  
8         0        3     2010     236500  

[5 rows x 38 columns]

In [53]:
#X,y ->feature, class label

X=new_house.drop('SalePrice',axis=1)
y=new_house['SalePrice']

In [55]:
#Model ->
#Kbest  #chisquare  #LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
x_new=SelectKBest(f_classif,k=5).fit_transform(X,y)
x_new

array([[6.000e+00, 1.656e+03, 2.000e+00, 5.280e+02, 0.000e+00],
       [7.000e+00, 2.110e+03, 2.000e+00, 5.220e+02, 0.000e+00],
       [5.000e+00, 1.629e+03, 2.000e+00, 4.820e+02, 0.000e+00],
       ...,
       [5.000e+00, 1.224e+03, 2.000e+00, 5.760e+02, 0.000e+00],
       [5.000e+00, 1.389e+03, 2.000e+00, 4.180e+02, 0.000e+00],
       [7.000e+00, 2.000e+03, 3.000e+00, 6.500e+02, 0.000e+00]])

In [56]:
x_new.shape

(1458, 5)

In [57]:
from sklearn.feature_selection import chi2
x_new=SelectKBest(chi2,k=10).fit_transform(X,y)
x_new

array([[1.0000000e+00, 5.2630110e+08, 3.1770000e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [4.0000000e+00, 5.2635303e+08, 1.1160000e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.0000000e+00, 5.2710501e+08, 1.3830000e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [2.9250000e+03, 9.2325118e+08, 2.0000000e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.9290000e+03, 9.2410007e+08, 1.0010000e+04, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [2.9300000e+03, 9.2415105e+08, 9.6270000e+03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]])

In [58]:
type(x_new) #n dimensional array

numpy.ndarray

In [59]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
rfe=RFE(model)
values=rfe.fit(X,y)

In [60]:
values

RFE(estimator=LogisticRegression())

In [62]:
values.n_features_

18

In [66]:
X.head(2)

Order        PID  MS SubClass  Lot Area  Overall Qual  Overall Cond  \
0      1  526301100           20     31770             6             5   
3      4  526353030           20     11160             7             5   

   Year Built  Year Remod/Add  Mas Vnr Area  BsmtFin SF 1  ...  Garage Area  \
0        1960            1960         112.0         639.0  ...        528.0   
3        1968            1968           0.0        1065.0  ...        522.0   

   Wood Deck SF  Open Porch SF  Enclosed Porch  3Ssn Porch  Screen Porch  \
0           210             62               0           0             0   
3             0              0               0           0             0   

   Pool Area  Misc Val  Mo Sold  Yr Sold  
0          0         0        5     2010  
3          0         0        4     2010  

[2 rows x 37 columns]

In [63]:
values.ranking_

array([ 1,  1,  7,  1, 10, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,  6,  1,
       16, 20, 15, 17, 13, 19, 11, 18,  1, 14,  1,  1,  2,  4,  8,  3,  5,
        1,  9,  1])

In [64]:
values.support_

array([ True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True, False, False, False, False, False,  True, False,
        True])