In [1]:
import pandas as pd
df=pd.read_csv('dataset/student_scores.csv')
df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [2]:
len(df)

25

In [3]:
X=df['Hours']
y=df['Scores']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [12]:
x_train.shape

(18,)

In [25]:
type(x_train)

pandas.core.series.Series

In [13]:
x_test.shape

(7,)

In [14]:
y_train.shape

(18,)

In [15]:
y_test.shape

(7,)

In [16]:
#build model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [17]:
lr

LinearRegression()

In [19]:
#train 
#code - fit
x_train_twodi=x_train.values.reshape(-1,1)
lr.fit(x_train_twodi,y_train) 

LinearRegression()

In [20]:
lr.coef_ #value of w

array([9.53227213])

In [21]:
lr.intercept_  #b - bias

2.9760987546639583

In [23]:
x=4.5
w=9.53227213
b=2.9760987546639583
y=w*x+b
print(y)

45.87132333966396


In [24]:
lr.predict([[4.5]])

array([45.87132335])

In [26]:
y_train

3     75
16    30
19    69
21    54
22    35
1     47
0     21
4     30
11    62
9     25
23    76
8     81
13    42
17    24
2     27
7     60
14    17
10    85
Name: Scores, dtype: int64

In [34]:
pred_value=lr.predict(x_test.values.reshape(-1,1))
pred_value

array([77.32782139, 28.71323351, 87.81332073, 45.87132335, 61.12295876,
       90.67300237, 17.27450695])

In [35]:
y_test

24    86
20    30
15    95
12    41
18    67
6     88
5     20
Name: Scores, dtype: int64

In [39]:
for x,y in zip(pred_value,y_test):
    print(f"pred: {int(x)} act: {y}")

pred: 77 act: 86
pred: 28 act: 30
pred: 87 act: 95
pred: 45 act: 41
pred: 61 act: 67
pred: 90 act: 88
pred: 17 act: 20


In [40]:
#evaluate
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae=mean_absolute_error(y_test,pred_value)
print(f"Mean absolute error {mae}")

Mean absolute error 4.756069196104083


In [41]:
mse=mean_squared_error(y_test,pred_value)
print(f"Mean squared error {mse}")

Mean squared error 28.764781093004082


In [44]:
#training data testing
#x_train,y_train

train_pred_value=lr.predict(x_train.values.reshape(-1,1)).round()
train_pred_value

array([84., 27., 74., 49., 39., 52., 27., 36., 59., 29., 69., 82., 34.,
       21., 33., 55., 13., 76.])

In [45]:
mae=mean_absolute_error(y_train,train_pred_value)
print(f"Mean absolute error {mae}")  #4.756069196104083

Mean absolute error 5.166666666666667


In [46]:
mse=mean_squared_error(y_train,train_pred_value)
print(f"Mean squared error {mse}")

Mean squared error 31.055555555555557


In [47]:
cars=pd.read_csv('dataset/mtcars.csv')
cars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [51]:
from sklearn.preprocessing import OrdinalEncoder
ordr=OrdinalEncoder()
cars['model']=ordr.fit_transform(cars['model'].values.reshape(-1,1))
cars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    17.0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    18.0  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2     4.0  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    12.0  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    13.0  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5    30.0  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6     6.0  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7    20.0  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8    19.0  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9    21.0  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10   22.0  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11   23.0  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12   24.0  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13   25.0  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14    1.0  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15   14.0  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    3.0  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17    8.0  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18   11.0  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19   28.0  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20   29.0  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21    5.0  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22    0.0  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23    2.0  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24   26.0  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25    9.0  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26   27.0  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27   15.0  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28   10.0  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29    7.0  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30   16.0  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31   31.0  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [52]:
X=cars.drop('disp',axis=1)
y=cars['disp']

In [53]:
X.head()

model   mpg  cyl   hp  drat     wt   qsec  vs  am  gear  carb
0   17.0  21.0    6  110  3.90  2.620  16.46   0   1     4     4
1   18.0  21.0    6  110  3.90  2.875  17.02   0   1     4     4
2    4.0  22.8    4   93  3.85  2.320  18.61   1   1     4     1
3   12.0  21.4    6  110  3.08  3.215  19.44   1   0     3     1
4   13.0  18.7    8  175  3.15  3.440  17.02   0   0     3     2

In [54]:
y

0     160.0
1     160.0
2     108.0
3     258.0
4     360.0
5     225.0
6     360.0
7     146.7
8     140.8
9     167.6
10    167.6
11    275.8
12    275.8
13    275.8
14    472.0
15    460.0
16    440.0
17     78.7
18     75.7
19     71.1
20    120.1
21    318.0
22    304.0
23    350.0
24    400.0
25     79.0
26    120.3
27     95.1
28    351.0
29    145.0
30    301.0
31    121.0
Name: disp, dtype: float64

In [ ]:
#split test 20%
#build model
#evaluate -> testing / training data
#mae / mse 